

<div class="row-fluid">
    <div class="span12" id="flip-scroll">
    <a data-id="" href="<?php echo $this->basePath();?>/application/administrador/agregaradministrador" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Agregar Administrador</a>
    <a data-id="" href="<?php echo $this->basePath();?>/application/administrador/index" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Listado de  Admin</a>
    <a data-id="" href="<?php echo $this->basePath();?>/application/empresa/agregarempresa" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Agregar Empresa</a>
    <a data-id="" href="<?php echo $this->basePath();?>/application/empresa/index" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Listado de Empresa</a>
    <a data-id="" href="<?php echo $this->basePath();?>/application/vehiculo/index" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Listado de Particulares</a>


</div>
