<?php
$title = 'Agregar Nuevo Administrador';
$this->headTitle($title);
?>

<div class="span12">
<?php

$form = $this->form;
$form->setAttributes(array(
    'action' => $this->url.'/application/administrador/agregaradministrador',
    'method' => 'post',
    'class'=>'form-horizontal'
));

$form->prepare();
echo $this->form()->openTag($form);
?>
<legend><?php echo $this->escapeHtml($title); ?></legend>
<?php echo $this->formRow($form->get('rol')->setValue('administrador'));?>
<div class="row-fluid">
<div class="control-group span6"><?php echo $this->formRow($form->get('nombre'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('login'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('pass'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('pass2'));?>
<?php if($_GET['m']==1){echo 'no coinciden los pass';} ?>
</div>
</div>
<div class="row-fluid">


</div>
<div class="row-fluid">
<div class="control-group span12 "><?php echo $this->formSubmit($form->get('submit'));?></div></div><?php echo $this->form()->closeTag();?> 
</div>