<?php
$title = 'Editar Administrador';
$this->headTitle($title);
?>

<div class="span12">
<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => $this->url.'/editar-administrador/'.$this->id,
    'method' => 'post',
    'class'=>'form-horizontal'
));

$form->prepare();
echo $this->form()->openTag($form);
?>
<legend><?php echo $this->escapeHtml($title); ?></legend>
<?php echo $this->formRow($form->get('rol')->setValue('administrador'));?>
<?php echo $this->formRow($form->get('_id'));?>
<?php echo $this->formRow($form->get('usuario_id'));?>
<div class="row-fluid">
<div class="control-group span6"><?php echo $this->formRow($form->get('nombre'));?></div>
<h3>Datos de Usuario</h3>
<div class="control-group span6"><?php echo $this->formRow($form->get('login'));?></div>
<?php if($_GET['m']==1){echo 'no coinciden los pass';} ?>
</div>
<div class="row-fluid">


</div>
<div class="row-fluid">
<div class="control-group span12 "><?php echo $this->formSubmit($form->get('submit'));?></div></div><?php echo $this->form()->closeTag();?> 
<a data-id="" href="javascript:history.back(1)" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>cancelar</a>
</div>