

 <div class="row-fluid">
    <div class="span12" id="flip-scroll">
        <a data-id="" href="/" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>< Atras</a>
         <a data-id="" href="<?php echo $this->basePath();?>/application/administrador/agregaradministrador" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Agregar Administrador</a>
      
         <br><br>
       <table class="table table-bordered table-hover">
             <thead class="cf"> <tr>
            <th>N°</th>
          <!--  <th>id</th>-->
            <th>nombre</th>
            <th>Usuario</th>
         <!--   <th>pass</th>-->
            <th>Operaciones</th>
        </tr> </thead>
        <?php $count = 1;   for($i=0;$i<$this->cantidad;$i++) {?>
       <tr>
        <td><?php echo $count++ ?></td>
      <!--  <td><?php// echo $this->valores[$i]['id']; ?></td>-->
        <td><?php echo $this->valores[$i]['nombre']; ?></td>
        <td><?php echo $this->valores[$i]['login']; ?></td>
     <!--   <td><?php// echo $this->valores[$i]['pass']; ?></td>-->
    <td><a data-id="<?php echo $this->valores[$i]['_id']; ?>" href="<?php echo $this->basePath();?>/application/administrador/eliminaradministrador?id=<?php echo $this->valores[$i]['_id'];?>" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Eliminar</a>
   <a data-id="<?php echo $this->valores[$i]['_id']; ?>" href="<?php echo $this->basePath();?>/editar-administrador/<?php echo $this->valores[$i]['_id'];?>" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Editar</a>
                
         </tr>
       <?php }; ?>
        </table>
    </div>
</div>
