<?php
$title = 'Agregar nuevo vehiculo';
$this->headTitle($title);
?>

<div class="span12">
<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => $this->url.'/application/vehiculo/agregarvehiculo',
    'method' => 'post',
    'class'=>'form-horizontal'
));

$form->prepare();
echo $this->form()->openTag($form);
?>
<legend><?php echo $this->escapeHtml($title); ?></legend>

<div class="row-fluid">
<div class="control-group span6"><?php echo $this->formRow($form->get('nombre_corto'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('chofer_nom'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('empresa_id'));?></div>
</div>

<div class="row-fluid">
<div class="control-group span12 "><?php echo $this->formSubmit($form->get('submit'));?></div></div><?php echo $this->form()->closeTag();?> 
</div>