<?php
$title = 'Agregar nuevo usuario';
$this->headTitle($title);
?>

<div class="span12">
<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => $this->url.'/editar/vehiculo/'.$this->id,
    'method' => 'post',
    'class'=>'form-horizontal'
));

$form->prepare();
echo $this->form()->openTag($form);
?>
<legend><?php echo $this->escapeHtml($title); ?></legend>
<?php echo $this->formRow($form->get('_id'));?>
<div class="row-fluid">
<div class="control-group span6"><?php echo $this->formRow($form->get('nombre_corto'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('chofer_nom'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('empresa_id'));?></div>
<div class="row-fluid">
<div class="control-group span12 "><?php echo $this->formSubmit($form->get('submit'));?></div></div><?php echo $this->form()->closeTag();?> 
</div>