<?php
$title = 'Editar vehiculo';
$this->headTitle($title);
?>

<div class="span12">
<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => $this->url.'/editar/vehiculo/'.$this->idempresa.'/'.$this->idvehiculo,
    'method' => 'post',
    'class'=>'form-horizontal'
));

$form->prepare();
echo $this->form()->openTag($form);
?>
<legend><?php echo $this->escapeHtml($title); ?></legend>
<?php echo $this->formRow($form->get('empresa_id'));?>
<?php echo $this->formRow($form->get('usuario_id'));?>
<?php echo $this->formRow($form->get('_id'));?>
<?php echo $this->formRow($form->get('rol')->setValue('vehiculo'));?>
<h3>datos del vehiculo</h3>
<div class="row-fluid">
<div class="control-group span6"><?php echo $this->formRow($form->get('nombre_corto'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('num_imei'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('num_sim'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('color_ruta'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('placa'));?></div>
<h3>datos del chofer</h3>
<div class="control-group span6"><?php echo $this->formRow($form->get('chofer_nom'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('chofer_telefono'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('email'));?></div>
<h3>datos del Usuario chofer</h3>
<div class="control-group span6"><?php echo $this->formRow($form->get('login'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('enviar'));?></div>
</div>

<div class="row-fluid">
<div class="control-group span12 "><?php echo $this->formSubmit($form->get('submit'));?></div></div><?php echo $this->form()->closeTag();?> 
<a data-id="" href="javascript:history.back(1)" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>cancelar</a>
 
</div>