<html lang="en">
    <head>
        <meta charset="utf-8">
    </head>
<style type="text/css">
table,tr,td,th
{  
border: 1px solid #000; 
border-collapse: collapse;
text-align: center;
}
     </style>
     <br>
     <br>

<?php  
//header('Content-Type: text/html; charset=utf-8');
header("Pragma: public");
header("Cache-Control: no-store, no-cache, must-revalidate");
header("Cache-Control: pre-check=0, post-check=0, max-age=0");
header("Pragma: no-cache");
header("Expires: 0");
header("Content-Transfer-Encoding: none");
header("Content-Type: application/vnd.ms-excel;");
header("Content-type: application/x-msexcel");
header("Content-Disposition: attachment; filename=Paradas_".date('Ymd').".xls");
    echo("<table>");
    echo("<tr style='font-weight: bold;'>");
    echo("<td>Id</td>");
    echo("<td>De</td>");
    echo("<td>Para</td>");
    echo("<td>Lat</td>");
    echo("<td>Lon</td>");
    echo("<td>Dirección</td>");
    echo("<td>Tiempo</td>");
     foreach($this->tramas as $key=>$trama){ ?>
            <tr>
            <td><?php echo $key+1; ?></td>
            <td><?php echo $trama['fecha_inicio']; ?></td>
            <td><?php echo $trama['fecha_fin']; ?></td>
            <td><?php echo $trama['latitude']?> </td> 
            <td><?php echo $trama['longitude']?> </td> 
            <td></td>
             <td><?php echo date("Y-m-d H:i:s",$trama['tiempo']); ?></td>

            </tr>
        <?php }?>

        </table>
</html>