<?php
$title = 'Informe sobre Kilometraje';
$this->headTitle($title);
?>
<div class="row-fluid">
<div class="span12" id="flip-scroll">
    <?php
    $form = $this->form;
    $form->setAttributes(array(
        'action' => $this->url . '/application/reporte/kilometraje',
        'method' => 'post',
        'class' => 'form-inline',
        'role' => 'form'
    ));

    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    <legend><?php echo $this->escapeHtml($title); ?></legend>
    <div class="control-group">
        <div class="form-group"><?php echo $this->formRow($form->get('usario_vehiculo')); ?></div>
        <div class="form-group"><?php echo $this->formRow($form->get('fechainicio')); ?></div>
        <div class="form-group"><?php echo $this->formRow($form->get('fechafin')); ?></div> 
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
    <?php echo $this->form()->closeTag(); ?> 
<!--    <button type="button" class="btn">Excel</button>
    <button type="button" class="btn">Imprimir</button>-->
    <br><br>
    <table class="table table-bordered table-hover">
    <thead class="cf"> <tr>
            <th>idMongo</th>
            <th>Nombre</th>
            <th>Tiempo</th>
            <th>Kilometraje</th>
            <th>Exeso de velocidad</th>
            <th>Quedar</th>
            <th>Consume de combustible</th>
        </tr> </thead>

</table>
</div>
    </div>








