<!DOCTYPE html>
<script src="<?php echo $this->ruta;?>/Language/language02-en-us.js" type="text/javascript"></script>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>GPSCAR</title>
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="" name="author" />
   <meta name="MobileOptimized" content="320">
   <!-- BEGIN GLOBAL MANDATORY STYLES -->          
   <link href="<?php echo $this->ruta;?>/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
   <link href="<?php echo $this->ruta;?>/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
   <link href="<?php echo $this->ruta;?>/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
   <!-- END GLOBAL MANDATORY STYLES -->
   <!-- BEGIN THEME STYLES --> 
   <link href="<?php echo $this->ruta;?>/assets/css/style-metronic.css" rel="stylesheet" type="text/css"/>
   <link href="<?php echo $this->ruta;?>/assets/css/style.css" rel="stylesheet" type="text/css"/>
   <link href="<?php echo $this->ruta;?>/assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>
   <link href="<?php echo $this->ruta;?>/assets/css/plugins.css" rel="stylesheet" type="text/css"/>
   <link href="<?php echo $this->ruta;?>/assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
   <link href="<?php echo $this->ruta;?>/assets/css/custom.css" rel="stylesheet" type="text/css"/>
   <link rel="stylesheet" href="<?php echo $this->ruta;?>/CSS/User.css" type="text/css" />
   <!-- END THEME STYLES -->
   <link rel="shortcut icon" href="<?php echo $this->ruta;?>/favicon.ico" />

   <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
   <!-- BEGIN CORE PLUGINS -->   
   <!--[if lt IE 9]>
   <script src="assets/plugins/respond.min.js"></script>
   <script src="assets/plugins/excanvas.min.js"></script> 
   <![endif]-->   
   <script src="<?php echo $this->ruta;?>/assets/plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
   <script src="<?php echo $this->ruta;?>/assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script> 
   <script src="<?php echo $this->ruta;?>/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
   <script src="<?php echo $this->ruta;?>/assets/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script>
   <script src="<?php echo $this->ruta;?>/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
   <script src="<?php echo $this->ruta;?>/assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>  
   <script src="<?php echo $this->ruta;?>/assets/plugins/jquery.cookie.min.js" type="text/javascript"></script>
   <script src="<?php echo $this->ruta;?>/assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script>-->
   <!-- END CORE PLUGINS -->
 <!--  <script type="text/javascript" src="<?php echo $this->ruta;?>/JS/jquery.easydrag.js"></script>
   <script type="text/javascript" src="<?php echo $this->ruta;?>/JS/ExceptionType.js"></script>
   <script type="text/javascript" src="<?php echo $this->ruta;?>/JS/ExceptionMessage.js"></script>
   <script type="text/javascript" src="<?php echo $this->ruta;?>/JS/User.js?v=20130520"></script>-->

   <!-- BEGIN PAGE LEVEL SCRIPTS -->
   <script src="<?php echo $this->ruta;?>/assets/scripts/app.js" type="text/javascript"></script>
   <!-- END PAGE LEVEL SCRIPTS -->
   <script>
      jQuery(document).ready(function() {    
         App.init();
      });
   </script>
   <!-- END JAVASCRIPTS -->
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed">
   <!-- BEGIN HEADER -->   
   <form method="post" action="User.aspx?id=<?php echo $this->hidUserID; ?>&amp;n=turismoche&amp;p=2UELRV216378f04" id="form1">
      <div class="header navbar navbar-inverse navbar-fixed-top">
         <!-- BEGIN TOP NAVIGATION BAR -->
         <div class="header-inner">
            <!-- BEGIN LOGO -->  
            <a class="navbar-brand" href="index.html">
            <img src="<?php echo $this->ruta;?>/assets/img/logo.png" alt="logo" class="img-responsive" />
            </a>
            <!-- END LOGO -->
            <!-- BEGIN RESPONSIVE MENU TOGGLER --> 
            <a href="javascript:;" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <img src="<?php echo $this->ruta;?>/assets/img/menu-toggler.png" alt="" />
            </a> 
            <!-- END RESPONSIVE MENU TOGGLER -->
            <!-- BEGIN TOP NAVIGATION MENU -->
               <ul class="nav navbar-nav pull-right">
               <!-- BEGIN NOTIFICATION DROPDOWN -->
                   <li class="dropdown" id="header_notification_bar">
                  <a href="/" class="dropdown-toggle"  data-hover="dropdown"
                     data-close-others="true">
                  <span >Monitor</span>
                  </a></li>
          <?php if($this->rol=='administrador'){?>
               <li class="dropdown" id="header_notification_bar">
                  <a href="<?php echo $this->url('admin') ?>" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
                     data-close-others="true">
                  <span >Administrar</span>
                  </a>
                  <ul class="dropdown-menu extended notification">
                     <li>
                          <a href="/application/administrador/agregaradministrador">
                              <span class="label label-icon label-success"><i class="fa fa-plus"></i></span>
                              Agregar Administrador
                              </a>
                     </li>
                     <li>
                          <a href="/application/administrador/index">
                              <span class="label label-icon label-success"><i class="fa fa-plus"></i></span>
                              Listado de Admin
                              </a>
                     </li>
                     <li>
                          <a href="/application/empresa/agregarempresa">
                              <span class="label label-icon label-success"><i class="fa fa-plus"></i></span>
                              Agregar Empresa 
                              </a>
                     </li><li>
                          <a href="/application/empresa/index">
                              <span class="label label-icon label-success"><i class="fa fa-plus"></i></span>
                              Listado de Empresa
                              </a>
                     </li>
                     <li>
                          <a href="/application/vehiculo/index">
                              <span class="label label-icon label-success"><i class="fa fa-plus"></i></span>
                              Listado de Particulares
                              </a>
                     </li>
                  </ul>
               </li>
               <?php  }?>
               <li class="dropdown" id="header_notification_bar">
               <a href="/application/reporte/movimiento" class="dropdown-toggle"  data-hover="dropdown"
                     data-close-others="true">
               <span >Estadísticas</span>
                  </a></li>
               <!-- END NOTIFICATION DROPDOWN -->
               <!-- BEGIN INBOX DROPDOWN -->
               <li class="dropdown" id="header_inbox_bar">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
                     data-close-others="true">
                  <i class="fa fa-envelope"></i>
                  <span class="badge">5</span>
                  </a>
                  <ul class="dropdown-menu extended inbox">
                     <li>
                        <p>You have 12 new messages</p>
                     </li>
                     <li>
                        <ul class="dropdown-menu-list scroller" style="height: 250px;">
                           <li>  
                              <a href="inbox.html?a=view">
                              <span class="photo"><img src="<?php echo $this->ruta;?>/assets/img/avatar2.jpg" alt=""/></span>
                              <span class="subject">
                              <span class="from">Lisa Wong</span>
                              <span class="time">Just Now</span>
                              </span>
                              <span class="message">
                              Vivamus sed auctor nibh congue nibh. auctor nibh
                              auctor nibh...
                              </span>  
                              </a>
                           </li>
                           <li>  
                              <a href="inbox.html?a=view">
                              <span class="photo"><img src="<?php echo $this->ruta;?>/assets/img/avatar3.jpg" alt=""/></span>
                              <span class="subject">
                              <span class="from">Richard Doe</span>
                              <span class="time">16 mins</span>
                              </span>
                              <span class="message">
                              Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh
                              auctor nibh...
                              </span>  
                              </a>
                           </li>
                           <li>  
                              <a href="inbox.html?a=view">
                              <span class="photo"><img src="<?php echo $this->ruta;?>/assets/img/avatar1.jpg" alt=""/></span>
                              <span class="subject">
                              <span class="from">Bob Nilson</span>
                              <span class="time">2 hrs</span>
                              </span>
                              <span class="message">
                              Vivamus sed nibh auctor nibh congue nibh. auctor nibh
                              auctor nibh...
                              </span>  
                              </a>
                           </li>
                           <li>  
                              <a href="inbox.html?a=view">
                              <span class="photo"><img src="<?php echo $this->ruta;?>//assets/img/avatar2.jpg" alt=""/></span>
                              <span class="subject">
                              <span class="from">Lisa Wong</span>
                              <span class="time">40 mins</span>
                              </span>
                              <span class="message">
                              Vivamus sed auctor 40% nibh congue nibh...
                              </span>  
                              </a>
                           </li>
                           <li>  
                              <a href="inbox.html?a=view">
                              <span class="photo"><img src="<?php echo $this->ruta;?>//assets/img/avatar3.jpg" alt=""/></span>
                              <span class="subject">
                              <span class="from">Richard Doe</span>
                              <span class="time">46 mins</span>
                              </span>
                              <span class="message">
                              Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh
                              auctor nibh...
                              </span>  
                              </a>
                           </li>
                        </ul>
                     </li>
                     <li class="external">   
                        <a href="inbox.html">See all messages <i class="m-icon-swapright"></i></a>
                     </li>
                  </ul>
               </li>
               <!-- END INBOX DROPDOWN -->
               <!-- BEGIN TODO DROPDOWN -->
               <li class="dropdown" id="header_task_bar">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                  <i class="fa fa-tasks"></i>
                  <span class="badge">5</span>
                  </a>
                  <ul class="dropdown-menu extended tasks">
                     <li>
                        <p>You have 12 pending tasks</p>
                     </li>
                     <li>
                        <ul class="dropdown-menu-list scroller" style="height: 250px;">
                           <li>  
                              <a href="#">
                                 <span class="task">
                                    <span class="desc">New release v1.2</span>
                                    <span class="percent">30%</span>
                                 </span>
                                 <span class="progress">
                                    <span style="width: 40%;" class="progress-bar progress-bar-success" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100">
                                       <span class="sr-only">40% Complete</span>
                                    </span>
                                 </span>
                              </a>
                           </li>
                           <li>  
                              <a href="#">
                              <span class="task">
                              <span class="desc">Application deployment</span>
                              <span class="percent">65%</span>
                              </span>
                              <span class="progress progress-striped">
                              <span style="width: 65%;" class="progress-bar progress-bar-danger" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">65% Complete</span>
                              </span>
                              </span>
                              </a>
                           </li>
                           <li>  
                              <a href="#">
                              <span class="task">
                              <span class="desc">Mobile app release</span>
                              <span class="percent">98%</span>
                              </span>
                              <span class="progress">
                              <span style="width: 98%;" class="progress-bar progress-bar-success" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">98% Complete</span>
                              </span>
                              </span>
                              </a>
                           </li>
                           <li>  
                              <a href="#">
                              <span class="task">
                              <span class="desc">Database migration</span>
                              <span class="percent">10%</span>
                              </span>
                              <span class="progress progress-striped">
                              <span style="width: 10%;" class="progress-bar progress-bar-warning" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">10% Complete</span>
                              </span>
                              </span>
                              </a>
                           </li>
                           <li>  
                              <a href="#">
                              <span class="task">
                              <span class="desc">Web server upgrade</span>
                              <span class="percent">58%</span>
                              </span>
                              <span class="progress progress-striped">
                              <span style="width: 58%;" class="progress-bar progress-bar-info" aria-valuenow="58" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">58% Complete</span>
                              </span>
                              </span>
                              </a>
                           </li>
                           <li>  
                              <a href="#">
                              <span class="task">
                              <span class="desc">Mobile development</span>
                              <span class="percent">85%</span>
                              </span>
                              <span class="progress progress-striped">
                              <span style="width: 85%;" class="progress-bar progress-bar-success" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">85% Complete</span>
                              </span>
                              </span>
                              </a>
                           </li>
                           <li>  
                              <a href="#">
                              <span class="task">
                              <span class="desc">New UI release</span>
                              <span class="percent">18%</span>
                              </span>
                              <span class="progress progress-striped">
                              <span style="width: 18%;" class="progress-bar progress-bar-important" aria-valuenow="18" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">18% Complete</span>
                              </span>
                              </span>
                              </a>
                           </li>
                        </ul>
                     </li>
                     <li class="external">   
                        <a href="#">See all tasks <i class="m-icon-swapright"></i></a>
                     </li>
                  </ul>
               </li>
               <!-- END TODO DROPDOWN -->
               <!-- BEGIN USER LOGIN DROPDOWN -->
               <li class="dropdown user">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                  <img alt="" src="<?php echo $this->ruta;?>/assets/img/avatar1_small.jpg"/>
                  <span class="username"><?php echo $this->nombre;?></span>
                  <i class="fa fa-angle-down"></i>
                  </a>
                  <ul class="dropdown-menu">
                     <li><a href="<?php echo $this->url('logout') ?>"><i class="fa fa-key"></i>Salir</a></li>
                     <?php if($this->rol=='empresa') { ?>
                     <li><a href="/application/index/perfil"><i class="fa fa-user"></i> Mí Cuenta</a></li>
                     <?php  } elseif($this->rol=='vehiculo'){?>
                     <li><a href="/application/index/editarpassvehiculousuario"><i class="fa fa-user"></i>Cambiar Pass</a></li> 
                     <?php }?>
                     <li><a href="page_calendar.html"><i class="fa fa-calendar"></i> My Calendar</a></li>
                     <li><a href="inbox.html"><i class="fa fa-envelope"></i> My Inbox <span class="badge badge-danger">3</span></a></li>
                     <li><a href="#"><i class="fa fa-tasks"></i> My Tasks <span class="badge badge-success">7</span></a></li>
                     <li class="divider"></li>
                     <li><a href="javascript:;" id="trigger_fullscreen"><i class="fa fa-move"></i> Full Screen</a></li>
                     <li><a href="extra_lock.html"><i class="fa fa-lock"></i> Lock Screen</a></li>
                     
                  </ul>
               </li>
               <!-- END USER LOGIN DROPDOWN -->
            </ul>
            <!-- END TOP NAVIGATION MENU -->
         </div>
         <!-- END TOP NAVIGATION BAR -->
      </div>
      <!-- END HEADER -->
      <div class="clearfix"></div>
      
      <input name="hidUserID" type="hidden" id="hidUserID" value="<?php echo $this->hidUserID; ?>" />
      <input name="hidLoginName" type="hidden" id="hidLoginName" value="<?php echo $this->nombre; ?>" />
      <input name="hidTimeZone" type="hidden" id="hidTimeZone" value="SA Pacific Standard Time" />
   </form>

   <?php
$title = 'Movimiento Global';

$this->headTitle($title);
?>
<div class="row-fluid">
<div class="span12" id="flip-scroll">

    <?php
    $form = $this->form;
    $form->setAttributes(array(
        'action' => $this->url . '/application/reporte/movimiento',
        'method' => 'post',
        'class' => 'form-inline',
        'role' => 'form'
    ));

    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    <legend><?php echo $this->escapeHtml($title); ?></legend>
    <h3><a href="/application/reporte/movimiento">movimiento</a></h3>
   <h3><a href="/application/reporte/parada">parada</a></h3>
   <h3><a href="/application/reporte/kilometraje">kilometrage</a></h3>
    <div class="control-group">
       <?php  if($this->rol =='administrador') {?> <div class="form-group"><?php echo $this->formRow($form->get('usario_empresa')); ?></div><?php  } ?>
        <div class="form-group"><?php echo $this->formRow($form->get('fechainicio')); ?></div>
        <div class="form-group"><?php echo $this->formRow($form->get('fechafin')); ?></div>
        <?php echo $this->formSubmit($form->get('submit')); ?>
        
    </div>
    <?php echo $this->form()->closeTag(); ?> 
     <div class="control-group">
    <div class="form-group"><a href="/application/reporte/excelmovimiento">Excel</a></div>
     </div>
<!--    
    <button type="button" class="btn">Imprimir</button>-->
    <br><br>
    <table class="table table-bordered table-hover">
    <thead class="cf"> <tr>
            <th>idMongo</th>
            <th>Nombre</th>
            <th>Tiempo</th>
            <th>Kilometraje</th>
            <th>Quedar</th>
            <th>Exeso de velocidad</th>
            <th>Work time</th>
        </tr> </thead>
        <?php foreach($this->tramas as $key=>$trama){ ?>
            <tr>
            <td><?php echo $key+1; ?></td>
            <td><?php echo $trama['chofer_nom']; ?></td>
            <td><?php echo $trama['fecha'];?></td>
            <td><?php echo $trama['total_km']; ?></td
            <td></td>
             <td></td>
              <td></td>
               <td></td>
            </tr>
        <?php }?>
    <!--<?php for ($i = 0; $i < $this->cantidad; $i++) { ?>
        <tr>
            <td><?php echo $this->valores[$i]['_id']; ?></td>
            <td><?php echo $this->valores[$i]['nombre_corto']; ?></td>
            <td><?php echo $this->valores[$i]['chofer']['chofer_nom']; ?></td>
            <td><?php echo $this->valores[$i]['nombre_empresa']; ?></td>
            <td><a data-id="<?php echo $this->valores[$i]['_id']; ?>" href="<?php //echo $this->basePath(); ?>/application/vehiculo/eliminarvehiculo?id=<?php echo $this->valores[$i]['_id']; ?>" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Eliminar</a>
                <a data-id="<?php echo $this->valores[$i]['_id']; ?>" href="<?php //echo $this->basePath(); ?>/editar/vehiculo/<?php echo $this->valores[$i]['_id']; ?>" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Editar</a>

        </tr>
    <?php }; ?> -->
         </table>

    </div>
</div>
</body>
</html>





