<?php
$title = 'Agregar nuevo empresa';
$this->headTitle($title);
?>

<div class="span12">
<?php

$form = $this->form;
$form->setAttributes(array(
    'action' => $this->url.'/application/empresa/agregarempresa',
    'method' => 'post',
    'class'=>'form-horizontal'
));

$form->prepare();
echo $this->form()->openTag($form);
?>
<legend><?php echo $this->escapeHtml($title); ?></legend>
<?php echo $this->formRow($form->get('rol')->setValue('empresa'));?>
<div class="row-fluid">
<div class="control-group span6"><?php echo $this->formRow($form->get('nombre'));?>
<div class="control-group span6"><?php echo $this->formRow($form->get('descripcion'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('ruc'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('direccion'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('telefono'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('email'));?></div>
<h3>datos del Usuario Empresa</h3>
<div class="control-group span6"><?php echo $this->formRow($form->get('login'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('pass'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('pass2'));?>
    <?php if($_GET['m']==1){echo 'no coinciden los pass';} ?>
    
 <div class="control-group span6"><?php echo $this->formRow($form->get('enviar'));?>   
<div class="row-fluid">
<div class="control-group span12 "><?php echo $this->formSubmit($form->get('submit'));?></div></div><?php echo $this->form()->closeTag();?> 
<a data-id="" href="javascript:history.back(1)" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>cancelar</a>
</div>




