

<div class="row-fluid">
    <div class="span12" id="flip-scroll">
   <a data-id="" href="/" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>< Atras</a>
         <a data-id="" href="<?php echo $this->basePath();?>/application/empresa/agregarempresa" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Agregar Empresa</a>
        
         <form name='form_busqueda'class="form-search" action='/application/empresa/index' method ="post">
                    <div class="control-group">
                    <label class="ra radio">Buscar:
                    <input type='text' name='texto' id="texto" placeholder="Nombre de empresa" />
                    <input type="submit" class="btn" name="submit" value="Buscar">
                    </div>
            </form>
         
         <br><br>
       <table class="table table-bordered table-hover">
             <thead class="cf"> <tr>
            <th>N°</th>
          <!--  <th>id</th>-->
            <th>nombre</th>
            <th>descripcion</th>
            <th>ruc</th>
            <th>Teléfono</th>
         <!--   <th>pass</th>-->
            <th>Operaciones</th>
        </tr> </thead>
        <?php $count = 1; for($i=0;$i<$this->cantidad;$i++) {?>
       <tr>
       <!-- <td><?php echo $this->valores[$i]['_id']; ?></td>-->
            <td><?php echo $count++ ?></td>
      <!--  <td><?php// echo $this->valores[$i]['id']; ?></td>-->
        <td><a href="<?php echo $this->basePath();?>/listar-vehiculo/<?php echo $this->valores[$i]['_id'];?>" ><?php echo $this->valores[$i]['nombre']; ?> </a></td>
        <td><?php echo $this->valores[$i]['descripcion']; ?></td>
        <td><?php echo $this->valores[$i]['ruc']; ?></td>
        <td><?php echo $this->valores[$i]['telefono']; ?></td>
     <!--   <td><?php// echo $this->valores[$i]['pass']; ?></td>-->
    <td><a data-id="<?php echo $this->valores[$i]['_id']; ?>" href="<?php echo $this->basePath();?>/editar-empresa/<?php echo $this->valores[$i]['_id'];?>" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Editar</a>
  <!--   <a data-id="<?php echo $this->valores[$i]['_id']; ?>" href="<?php echo $this->basePath();?>/application/index/eliminarusuario?id=<?php echo $this->valores[$i]['_id'];?>" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Eliminar</a>
          -->  
         <a data-id="<?php echo $this->valores[$i]['_id']; ?>" href="<?php echo $this->basePath();?>/listar-vehiculo/<?php echo $this->valores[$i]['_id'];?>" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Listar Vehículos</a>
         </tr>
       <?php }; ?>
        </table>
    </div>
</div>
