 
      
      
   <div class="row-fluid">
    <div class="span12" id="flip-scroll">
       
         <br><br>
<?php
$title = 'Editar vehiculo';
$this->headTitle($title);
?>
<?php echo $this->mensaje;?>
<div class="span12">
<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => $this->url.'/application/index/editarpassvehiculousuario',
    'method' => 'post',
    'class'=>'form-horizontal'
));
$form->prepare();
echo $this->form()->openTag($form);
?>
<legend><?php echo $this->escapeHtml($title); ?></legend>
<div class="row-fluid">
<div class="control-group span6"><?php echo $this->formRow($form->get('passantiguo'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('pass'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('pass2'));?></div>
<div class="control-group span12 "><?php echo $this->formSubmit($form->get('submit'));?></div></div><?php echo $this->form()->closeTag();?> 
<a data-id="" href="javascript:history.back(1)" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>cancelar</a>
</div>
    </div>
</div>
  



