 <a data-id="" href="<?php echo $this->basePath();?>/application/index/logout" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>serrar Session</a>  
<? if ($this->rol=='administrador'){  ?>
  <a data-id="" href="<?php echo $this->basePath();?>/application/administrador/admin" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>admin</a>     
 <?php  } elseif($this->rol=='empresa'){ echo $this->rol;
  
  }else echo $this->rol;?>
  