<!DOCTYPE html>
<script src="<?php echo $this->ruta;?>/Language/language02-en-us.js" type="text/javascript"></script>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>GPSCAR</title>
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="" name="author" />
   <meta name="MobileOptimized" content="320">
   <!-- BEGIN GLOBAL MANDATORY STYLES -->          
   <link href="<?php echo $this->ruta;?>/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
   <link href="<?php echo $this->ruta;?>/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
   <link href="<?php echo $this->ruta;?>/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
   <!-- END GLOBAL MANDATORY STYLES -->
   <!-- BEGIN THEME STYLES --> 
   <link href="<?php echo $this->ruta;?>/assets/css/style-metronic.css" rel="stylesheet" type="text/css"/>
   <link href="<?php echo $this->ruta;?>/assets/css/style.css" rel="stylesheet" type="text/css"/>
   <link href="<?php echo $this->ruta;?>/assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>
   <link href="<?php echo $this->ruta;?>/assets/css/plugins.css" rel="stylesheet" type="text/css"/>
   <link href="<?php echo $this->ruta;?>/assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
   <link href="<?php echo $this->ruta;?>/assets/css/custom.css" rel="stylesheet" type="text/css"/>
   <link rel="stylesheet" href="<?php echo $this->ruta;?>/CSS/User.css" type="text/css" />
   <!-- END THEME STYLES -->
   <link rel="shortcut icon" href="<?php echo $this->ruta;?>/favicon.ico" />

   <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
   <!-- BEGIN CORE PLUGINS -->   
   <!--[if lt IE 9]>
   <script src="assets/plugins/respond.min.js"></script>
   <script src="assets/plugins/excanvas.min.js"></script> 
   <![endif]-->   
   <script src="<?php echo $this->ruta;?>/assets/plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
   <script src="<?php echo $this->ruta;?>/assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script> 
   <script src="<?php echo $this->ruta;?>/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
   <script src="<?php echo $this->ruta;?>/assets/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script>
   <script src="<?php echo $this->ruta;?>/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
   <script src="<?php echo $this->ruta;?>/assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>  
   <script src="<?php echo $this->ruta;?>/assets/plugins/jquery.cookie.min.js" type="text/javascript"></script>
   <script src="<?php echo $this->ruta;?>/assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script>
   <!-- END CORE PLUGINS -->
   <script type="text/javascript" src="<?php echo $this->ruta;?>/JS/jquery.easydrag.js"></script>
   <script type="text/javascript" src="<?php echo $this->ruta;?>/JS/ExceptionType.js"></script>
   <script type="text/javascript" src="<?php echo $this->ruta;?>/JS/ExceptionMessage.js"></script>
   <script type="text/javascript" src="<?php echo $this->ruta;?>/JS/User.js?v=20130520"></script>

   <!-- BEGIN PAGE LEVEL SCRIPTS -->
   <script src="<?php echo $this->ruta;?>/assets/scripts/app.js" type="text/javascript"></script>
   <!-- END PAGE LEVEL SCRIPTS -->
   <script>
      jQuery(document).ready(function() {    
         App.init();
      });
   </script>
   <!-- END JAVASCRIPTS -->
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed">
   <!-- BEGIN HEADER -->   
   <form method="post" action="User.aspx?id=9564&amp;n=turismoche&amp;p=2UELRV216378f04" id="form1">
      <div class="header navbar navbar-inverse navbar-fixed-top">
         <!-- BEGIN TOP NAVIGATION BAR -->
         <div class="header-inner">
            <!-- BEGIN LOGO -->  
            <a class="navbar-brand" href="index.html">
            <img src="<?php echo $this->ruta;?>/assets/img/logo.png" alt="logo" class="img-responsive" />
            </a>
            <!-- END LOGO -->
            <!-- BEGIN RESPONSIVE MENU TOGGLER --> 
            <a href="javascript:;" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <img src="<?php echo $this->ruta;?>/assets/img/menu-toggler.png" alt="" />
            </a> 
            <!-- END RESPONSIVE MENU TOGGLER -->
            <!-- BEGIN TOP NAVIGATION MENU -->
            <ul class="nav navbar-nav pull-right">
               <!-- BEGIN NOTIFICATION DROPDOWN -->
               
          <?php if($this->rol=='administrador'){?>
               <li class="dropdown" id="header_notification_bar">
                  <a href="<?php echo $this->url('admin') ?>" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
                     data-close-others="true">
                  <span >ADMIN</span>
                  </a>
                  <ul class="dropdown-menu extended notification">
                     <li>
                          <a href="<?php echo $this->url('admin') ?>">
                              <span class="label label-icon label-success"><i class="fa fa-plus"></i></span>
                              ADmin. 
                              </a>
                     </li>
                  </ul>
               </li><?php  }?>
               <!-- END NOTIFICATION DROPDOWN -->
               <!-- BEGIN INBOX DROPDOWN -->
               <li class="dropdown" id="header_inbox_bar">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
                     data-close-others="true">
                  <i class="fa fa-envelope"></i>
                  <span class="badge">5</span>
                  </a>
                  <ul class="dropdown-menu extended inbox">
                     <li>
                        <p>You have 12 new messages</p>
                     </li>
                     <li>
                        <ul class="dropdown-menu-list scroller" style="height: 250px;">
                           <li>  
                              <a href="inbox.html?a=view">
                              <span class="photo"><img src="./assets/img/avatar2.jpg" alt=""/></span>
                              <span class="subject">
                              <span class="from">Lisa Wong</span>
                              <span class="time">Just Now</span>
                              </span>
                              <span class="message">
                              Vivamus sed auctor nibh congue nibh. auctor nibh
                              auctor nibh...
                              </span>  
                              </a>
                           </li>
                           <li>  
                              <a href="inbox.html?a=view">
                              <span class="photo"><img src="./assets/img/avatar3.jpg" alt=""/></span>
                              <span class="subject">
                              <span class="from">Richard Doe</span>
                              <span class="time">16 mins</span>
                              </span>
                              <span class="message">
                              Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh
                              auctor nibh...
                              </span>  
                              </a>
                           </li>
                           <li>  
                              <a href="inbox.html?a=view">
                              <span class="photo"><img src="./assets/img/avatar1.jpg" alt=""/></span>
                              <span class="subject">
                              <span class="from">Bob Nilson</span>
                              <span class="time">2 hrs</span>
                              </span>
                              <span class="message">
                              Vivamus sed nibh auctor nibh congue nibh. auctor nibh
                              auctor nibh...
                              </span>  
                              </a>
                           </li>
                           <li>  
                              <a href="inbox.html?a=view">
                              <span class="photo"><img src="./assets/img/avatar2.jpg" alt=""/></span>
                              <span class="subject">
                              <span class="from">Lisa Wong</span>
                              <span class="time">40 mins</span>
                              </span>
                              <span class="message">
                              Vivamus sed auctor 40% nibh congue nibh...
                              </span>  
                              </a>
                           </li>
                           <li>  
                              <a href="inbox.html?a=view">
                              <span class="photo"><img src="./assets/img/avatar3.jpg" alt=""/></span>
                              <span class="subject">
                              <span class="from">Richard Doe</span>
                              <span class="time">46 mins</span>
                              </span>
                              <span class="message">
                              Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh
                              auctor nibh...
                              </span>  
                              </a>
                           </li>
                        </ul>
                     </li>
                     <li class="external">   
                        <a href="inbox.html">See all messages <i class="m-icon-swapright"></i></a>
                     </li>
                  </ul>
               </li>
               <!-- END INBOX DROPDOWN -->
               <!-- BEGIN TODO DROPDOWN -->
               <li class="dropdown" id="header_task_bar">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                  <i class="fa fa-tasks"></i>
                  <span class="badge">5</span>
                  </a>
                  <ul class="dropdown-menu extended tasks">
                     <li>
                        <p>You have 12 pending tasks</p>
                     </li>
                     <li>
                        <ul class="dropdown-menu-list scroller" style="height: 250px;">
                           <li>  
                              <a href="#">
                              <span class="task">
                              <span class="desc">New release v1.2</span>
                              <span class="percent">30%</span>
                              </span>
                              <span class="progress">
                              <span style="width: 40%;" class="progress-bar progress-bar-success" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">40% Complete</span>
                              </span>
                              </span>
                              </a>
                           </li>
                           <li>  
                              <a href="#">
                              <span class="task">
                              <span class="desc">Application deployment</span>
                              <span class="percent">65%</span>
                              </span>
                              <span class="progress progress-striped">
                              <span style="width: 65%;" class="progress-bar progress-bar-danger" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">65% Complete</span>
                              </span>
                              </span>
                              </a>
                           </li>
                           <li>  
                              <a href="#">
                              <span class="task">
                              <span class="desc">Mobile app release</span>
                              <span class="percent">98%</span>
                              </span>
                              <span class="progress">
                              <span style="width: 98%;" class="progress-bar progress-bar-success" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">98% Complete</span>
                              </span>
                              </span>
                              </a>
                           </li>
                           <li>  
                              <a href="#">
                              <span class="task">
                              <span class="desc">Database migration</span>
                              <span class="percent">10%</span>
                              </span>
                              <span class="progress progress-striped">
                              <span style="width: 10%;" class="progress-bar progress-bar-warning" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">10% Complete</span>
                              </span>
                              </span>
                              </a>
                           </li>
                           <li>  
                              <a href="#">
                              <span class="task">
                              <span class="desc">Web server upgrade</span>
                              <span class="percent">58%</span>
                              </span>
                              <span class="progress progress-striped">
                              <span style="width: 58%;" class="progress-bar progress-bar-info" aria-valuenow="58" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">58% Complete</span>
                              </span>
                              </span>
                              </a>
                           </li>
                           <li>  
                              <a href="#">
                              <span class="task">
                              <span class="desc">Mobile development</span>
                              <span class="percent">85%</span>
                              </span>
                              <span class="progress progress-striped">
                              <span style="width: 85%;" class="progress-bar progress-bar-success" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">85% Complete</span>
                              </span>
                              </span>
                              </a>
                           </li>
                           <li>  
                              <a href="#">
                              <span class="task">
                              <span class="desc">New UI release</span>
                              <span class="percent">18%</span>
                              </span>
                              <span class="progress progress-striped">
                              <span style="width: 18%;" class="progress-bar progress-bar-important" aria-valuenow="18" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">18% Complete</span>
                              </span>
                              </span>
                              </a>
                           </li>
                        </ul>
                     </li>
                     <li class="external">   
                        <a href="#">See all tasks <i class="m-icon-swapright"></i></a>
                     </li>
                  </ul>
               </li>
               <!-- END TODO DROPDOWN -->
               <!-- BEGIN USER LOGIN DROPDOWN -->
               <li class="dropdown user">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                  <img alt="" src="<?php echo $this->ruta;?>/assets/img/avatar1_small.jpg"/>
                  <span class="username"><?php echo $this->nombre;?></span>
                  <i class="fa fa-angle-down"></i>
                  </a>
                  <ul class="dropdown-menu">
                     <li><a href="<?php echo $this->url('logout') ?>"><i class="fa fa-user"></i> Logout</a></li> 
                     <li><a href="extra_profile.html"><i class="fa fa-user"></i> My Profile</a></li>
                     <li><a href="page_calendar.html"><i class="fa fa-calendar"></i> My Calendar</a></li>
                     <li><a href="inbox.html"><i class="fa fa-envelope"></i> My Inbox <span class="badge badge-danger">3</span></a></li>
                     <li><a href="#"><i class="fa fa-tasks"></i> My Tasks <span class="badge badge-success">7</span></a></li>
                     <li class="divider"></li>
                     <li><a href="javascript:;" id="trigger_fullscreen"><i class="fa fa-move"></i> Full Screen</a></li>
                     <li><a href="extra_lock.html"><i class="fa fa-lock"></i> Lock Screen</a></li>
                     <li><a href="login.html"><i class="fa fa-key"></i> Log Out</a></li>
                  </ul>
               </li>
               <!-- END USER LOGIN DROPDOWN -->
            </ul>
            <!-- END TOP NAVIGATION MENU -->
         </div>
         <!-- END TOP NAVIGATION BAR -->
      </div>
      <!-- END HEADER -->
      <div class="clearfix"></div>
      <div id="divExceptionMessageDiv" style="border: 1px #CCCCCC solid; width: 400px; position: absolute; z-index: 9999;">
           <div id="divExceptionMessageDivTitle" style="background-color: #EFEFEF; height: 25px;">
               <table width="100%" border="0">
                   <tr>
                       <td>
                           <b>
                              <script type="text/javascript">
                                writePage(userPage.warnTitle);
                              </script>
                           </b>
                           <input id="chkAlarm" type="checkbox" value="" onclick="clkChangeAlarmSound(this.checked)" />
                           <script type="text/javascript">
                              writePage(userPage.warnSound);
                           </script>
                           <a href="javascript:void(0)" id="clearMessage" onclick="return confirm(geofencesPage.delGeoConfirm + '?') ? ClearHomeMessage() : void (null);">
                              <script type="text/javascript">
                                writePage(allPage.clear);
                              </script>
                           </a>
                       </td>
                       <td width="30">
                          <img src="icons/iw_min.gif" border="0" onclick="showExceptionMessageDiv(0);" style="cursor: pointer;" />
                          <img src="icons/iw_max.gif" border="0" onclick="showExceptionMessageDiv(1);" style="cursor: pointer;" />
                       </td>
                   </tr>
               </table>
           </div>
           <div id="divExceptionMessageDivInfo" style="height: 125px; background-color: White; overflow-y: auto; display: none;">
           </div>
      </div>
      <!-- BEGIN CONTAINER -->      
      <div class="page-container back-gps">
         <iframe id="MainBox" style="height: 100%; width: 100%" scrolling="no" frameborder="0"></iframe>
      </div>

      <input name="hidUserID" type="hidden" id="hidUserID" value="9564" />
      <input name="hidLoginName" type="hidden" id="hidLoginName" value="turismoche" />
      <input name="hidTimeZone" type="hidden" id="hidTimeZone" value="SA Pacific Standard Time" />
   </form>
</body>
</html>

<!--<? if ($this->rol=='administrador'){  ?>
 <div>
    <div  id="flip-scroll">
         <br><br>
       <table  width="250" class=" table-bordered table-hover">
             <thead class="cf"> <tr>
                     <tr>
            <th><form name='form_busqueda'class="form-search" action='/application/index/index' method ="post">
                    <div class="control-group">
                    <input type='text' name='texto' id="texto" placeholder="Nombre de empresa" />
                    <input type="submit" class="btn" name="submit" value="Buscar">
                    </div>
            </form></th>
        </tr>
            <th>Empresas</th>
        </tr> </thead>
        <?php $count = 1; for($i=0;$i<$this->cantidad;$i++) {?>
       <tr>
<td><a href="<?php echo $this->basePath();?>/application/index/index?id=<?php echo $this->valores[$i]['_id'];?>" ><?php echo $this->valores[$i]['nombre']; ?> (<?php echo $this->valores[$i]['cantidad']; ?>) </a></td>
       <?php }; ?>
        </table><br>
         <table width="250"  class=" table-bordered table-hover">
             <thead class="cf"> <tr>
            <th>Vehículos</th>
        </tr>    <tr>
            <th><form name='form'class="form-search" action='/application/index/index' method ="post">
                    <div class="control-group">
                    <input type='text' name='vehiculo' id="texto" placeholder="nombre o placa" />
                    <input type="submit" class="btn" name="submit" value="Buscar">
                    </div>
            </form></th>
        </tr>
             <tr>
                 <th><a href="#">todos</a>/<a href="#" >on line</a>/<a href="#">off line</a></th>
        </tr> </thead>
        <?php for($i=0;$i<$this->cantidadVehiculo;$i++) {?>
       <tr>
        <td><?php echo $this->vehiculo[$i]['nombre_corto']; ?> (<?php echo $this->vehiculo[$i]['placa']; ?>) </a></td>
       <?php }; ?>
        </table>
    </div>
</div>
      <?php  } elseif($this->rol=='empresa'){ 
      ?>  <table width="250" class=" table-bordered table-hover">
             <thead class="cf"> <tr>
            <th>Empresa</th>
        </tr> </thead>
       <tr>
        <td><?php echo $this->valores[0]['nombre']; ?> (<?php echo $this->valores[0]['cantidad']; ?>) </a></td>
        </table> <br>
          <table width="250"  class=" table-bordered table-hover">
             <thead class="cf"> <tr>
            <th>Vehículos</th>
        </tr>    
        <tr>
            <th><form name='form'class="form-search" action='/application/index/index' method ="post">
                    <div class="control-group">
                    <input type='text' name='vehiculo' id="texto" placeholder="nombre o placa" />
                    <input type="submit" class="btn" name="submit" value="Buscar">
                    </div>
            </form></th>
        </tr>
             <tr>
                 <th><a href="<?php echo $this->basePath();?>/application/index/index?estado=1">todos</a>/<a href="<?php echo $this->basePath();?>/application/index/index?estado=2" >on line</a>/<a href="<?php echo $this->basePath();?>/application/index/index?estado=3">off line</a></th>
        </tr> </thead>
        <?php for($i=0;$i<$this->cantidadVehiculo;$i++) {?>
       <tr>
        <td><a href="<?php echo $this->basePath();?>/application/index/index?detalle=<?php echo $this->vehiculo[$i]['_id']; ?>"><?php echo $this->vehiculo[$i]['nombre_corto']; ?> (<?php echo $this->vehiculo[$i]['placa']; ?>) </a></td>
       <?php }; ?>
       </table>
    <input name="hidUserID" type="hidden" id="hidUserID" value="<?php echo $this->hidUserID; ?>" />
    <input name="hidLoginName" type="hidden" id="hidLoginName" value="<?php echo $this->nombre; ?>" />
    <input name="hidTimeZone" type="hidden" id="hidTimeZone" value="SA Pacific Standard Time" /><?php
  }else {?>
  <table width="250" class=" table-bordered table-hover">
        <thead class="cf"> <tr>
        <th>Vehículo</th>
    </tr></thead>
   <tr>
    <td><?php echo $this->valores[0]['nombre_corto']; ?> (<?php echo $this->valores[0]['placa']; ?>) </a></td>
    </table> <?php } ?> -->
  