<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
   <meta charset="utf-8" />
   <title>GPSCAR</title>
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="" name="author" />
   <meta name="MobileOptimized" content="320">
         
   <link href="assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
   <link href="assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
   <link href="assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>

   <link rel="stylesheet" type="text/css" href="assets/plugins/select2/select2_metro.css" />

   <link href="assets/css/style-metronic.css" rel="stylesheet" type="text/css"/>
   <link href="assets/css/style.css" rel="stylesheet" type="text/css"/>
   <link href="assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>
   <link href="assets/css/plugins.css" rel="stylesheet" type="text/css"/>
   <link href="assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
   <link href="assets/css/pages/login-soft.css" rel="stylesheet" type="text/css"/>
   <link href="assets/css/custom.css" rel="stylesheet" type="text/css"/>
   <link rel="shortcut icon" href="favicon.ico" />
</head>
<body class="login">
   <div class="logo">
      <img src="assets/img/logo-big.png" alt="" /> 
   </div>
   <div class="content">
   		<?php

		$form = $this->form;
		$form->setAttributes(array(
		    'action' => $this->url.'/login',
		    'method' => 'post',
		    'class'=>'login-form'
		));

		$form->prepare();
		echo $this->form()->openTag($form);
		?>
         <h3 class="form-title"><?php echo $this->mensaje; ?></h3>
         <div class="alert alert-danger display-hide">
            <button class="close" data-close="alert"></button>
            <span>Ingresar usuario y contraseña.</span>
         </div>
         <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Usuario</label>
            <div class="input-icon">
               <i class="fa fa-user"></i>
               <?php echo $this->formRow($form->get('login'));?>               
            </div>
         </div>
         <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Contraseña</label>
            <div class="input-icon">
               <i class="fa fa-lock"></i>
               <?php echo $this->formRow($form->get('pass'));?>
            </div>
         </div>
         <div class="form-actions">
         	<!--<?php echo $this->formSubmit($form->get('submit'));?>-->
            <button type="submit" class="btn blue pull-right">
            	Ingresar <i class="m-icon-swapright m-icon-white"></i>
            </button>            
         </div>
      	<?php echo $this->form()->closeTag();?>      
   </div>
   <div class="copyright">
      2013 &copy; GPSCAR - INNOVATIONS SYSTEMS.
   </div> 
   <!--[if lt IE 9]>
   <script src="assets/plugins/respond.min.js"></script>
   <script src="assets/plugins/excanvas.min.js"></script> 
   <![endif]-->   
   <script src="assets/plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
   <script src="assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
   <script src="assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
   <script src="assets/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script>
   <script src="assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
   <script src="assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>  
   <script src="assets/plugins/jquery.cookie.min.js" type="text/javascript"></script>
   <script src="assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script>
   <script src="assets/plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
   <script src="assets/plugins/backstretch/jquery.backstretch.min.js" type="text/javascript"></script>
   <script type="text/javascript" src="assets/plugins/select2/select2.min.js"></script>
   <script src="assets/scripts/app.js" type="text/javascript"></script>
   <script src="assets/scripts/login-soft.js" type="text/javascript"></script>      
   <script>
      jQuery(document).ready(function() {     
        App.init();
        Login.init();
      });
   </script>
</body>
</html>